### ISSUE TITLE
🐐 What Aditya should work on

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#103]
**Type**: frontend

**FOF**: 5

## Description
Here's what I want you to finish:
- Resource search bar (#59)
  - Implement search functionality based on resource name
- Address search bar (#60)
  - Implement location search using Sophia's PR
-  Search carousel (#70)
   - Implement filtering using Esther's PR
- All filters search (#71) 
  - Implement search functionality using selected criteria
- Mobile support (#101)
  - Make the map view mobile responsive
  - Note that the mobile search bar pops out both the resource/address search bar 

## Screenshot
<img width="760" alt="image" src="https://user-images.githubusercontent.com/45826922/232620567-37f14ca9-58fd-4679-b62c-092bd38d400e.png">
<img width="205" alt="image" src="https://user-images.githubusercontent.com/45826922/232620751-fbe50e38-1b0d-4325-a55b-8fab7d6eaa08.png">
<img width="699" alt="image" src="https://user-images.githubusercontent.com/45826922/232622048-c5267add-9c48-4325-9032-3fb234e29483.png">

## Todo

- [ ] Finalize search functionality for all filtering methods
- [ ] Make the map view mobile responsive
- [ ] Make all the designs match Figma for both desktop and mobile
  - Refer to the screenshots above 

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)
