### ISSUE TITLE
% Modularize confirmation modal 

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#14]
**Type**: client

**FOF**: 1

## Description
- Currently, we have an existing confirmation modal that looks like this:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/45826922/221067591-f6283639-408f-44ad-aa2f-bd13bfd0afff.png">
- We want to modularize this component to support the accept/reject modals on Figma

## Screenshot
<img width="263" alt="image" src="https://user-images.githubusercontent.com/45826922/221067672-c440c9b6-0b77-4d8c-889c-ca99888af868.png">
<img width="274" alt="image" src="https://user-images.githubusercontent.com/45826922/221067712-d264e0f6-2f3d-494b-9cdf-b0884c70f0ff.png">

## Existing `<Confirm />` modal usage
- https://github.com/ClearPathNYC/clearpath-web/blob/master/src/components/confirm/index.tsx
- https://github.com/ClearPathNYC/clearpath-web/blob/master/src/hooks/use-apply-support-modal/index.tsx

## Todo

- [ ] Modularize the `<Confirm />` component to accept relevant `props`
- [ ] Create an instance of the accept modal on Figma
- [ ] Create an instance of the reject modal on Figma

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)
