### ISSUE TITLE
🤔 Create nonprofit category screen

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#36]
**Type**: client

**FOF**: 1

## Description
- We want to enable nonprofit to select which nonprofit category they fall under
  - Outreach and Tracking Interest
  - Reviewing and Processing Applicants 

## Screenshot
<img width="648" alt="image" src="https://user-images.githubusercontent.com/45826922/222598398-b9427f81-3a62-449b-8ea7-2f6630e5a5b0.png">

## Todo

- [ ] Retrieve the category images from Figma
  - Ask Emily how to do that
- [ ] Create the category cards
- [ ] Implement the select functionality 

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- MPC!
