### ISSUE TITLE
📃 Integrate remaining registration screens

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#42]
**Type**: client

**FOF**: 2

## Description
- We want to integrate the Details and Claim Organization pages with our Formik screens
- Check out #41 for an demo deployment
  -  https://clearpath-jwkv2bpds-hack4impact1.vercel.app/signin
- NOTE: A lot of logic in the demo deployment is hard-coded/incorrect
  - Feel free to reference the changes but don't feel obligated to follow them 

## Screenshot
<img width="454" alt="image" src="https://user-images.githubusercontent.com/45826922/223525368-29d03bcf-9b94-459d-babe-297f09146716.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/45826922/223525425-a0448134-637e-47c4-9251-3e7a7cdfe9a6.png">

## Todo

- [ ] Integrate the Details screen
- [ ] Integrate the Claim Organization screen
  - We should autofill the form if an existing organization is claimed
- [ ] Support "Next/Submit" functionality based on which screen the user is on  

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- Code Integration!
