### ISSUE TITLE
🔌 Connect confirmation toasts

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#46]
**Type**: client

**FOF**: 2

## Description
- We want to display the confirmation modals on their respective event triggers

## Screenshot
<img width="231" alt="image" src="https://user-images.githubusercontent.com/45826922/223538067-b2606890-9d9b-4a3f-9395-3591c2b3cb68.png">

## Todo

- [ ] Connect accept toast
- [ ] Connect decline toast
- [ ] Connect email toast
- [ ] Connect update toast

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- Code integration
