### ISSUE TITLE
☠️ Validate registration form

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#48]
**Type**: client

**FOF**: 2

## Description
- We want to check for valid form inputs before allowing the nonprofit admin to continue to the next screen

## Screenshot
<img width="442" alt="image" src="https://user-images.githubusercontent.com/45826922/224169533-1ec499b1-0273-43ad-b04d-6c3d0ccf4dcd.png">

## Todo

- [x] Check to make sure that required fields are populated
- [x] Check to make sure that structured inputs (email, phone number, etc.) are valid
- [x] Check to make sure that email addresses are unique to the nonprofit database
- [x] Check to make sure that passwords match and meet secure "requirement"

## Links

- Talk to Aditya about form validation ideas and how to check for unique emails
- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- Formik Validation!
