### ISSUE TITLE
🌎 Flesh out map view

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#57]
**Type**: client

**FOF**: 3

## Description
- We want to refactor the home page (`/dashboard`) to display the map view

## Screenshot
<img width="571" alt="image" src="https://user-images.githubusercontent.com/45826922/227430065-fde9dd32-cf9a-416e-a884-bf4947873ee5.png">

## Todo

- [ ] Remove the category sidebar
- [ ] Flesh out the general structure of the map view including the header, search bar, and full size map
- [ ] Start working on mobile responsiveness based on Emily's upcoming designs

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- Frontend!
- Maps!
