### ISSUE TITLE
🔐 Integrate nonprofit auth

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#58]
**Type**: full stack

**FOF**: 3

## Description
- Connect the sign-in page to the nonprofit dashboard when the user authenticates under an organization account
- If the nonprofit isn't approved yet by ClearPath, we want to take them to the pending screen

## Todo

- [ ] Detect a nonprofit login on `/signin`
- Upon success nonprofit login, direct the admin to...
  - [ ] pending page if the organization isn't yet approved
  - [ ] nonprofit dashboard if the organization is approve
- [ ] Reconfigure the protection of organization routes  

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- Authentication
- Redux
- Protected Routes
