### ISSUE TITLE
🔍 Create address search bar

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#60]
**Type**: client

**FOF**: 3

## Description
- We want to enable users to search for resources by location
- Utilize Google Maps API to populate dropdown with search recommendations
- Refer to #7 and #10 for utilizing the `<Input />` component
- Check out something similar we did on Brink with [SearchAddress.tsx](https://github.com/stephen-puiszis/brink-web/blob/main/src/components/search/SearchAddress.tsx)

## Screenshot
- Build out the search bar using ClearPath's `<Input />` component

<img width="793" alt="image" src="https://user-images.githubusercontent.com/45826922/227853762-24d187c2-eef2-43a1-91b3-e76de02b499e.png">

## Todo

- [ ] Create the address search bar
- [ ] Connect to Google Maps API
  - Take a look at [the map implementation](https://github.com/ClearPathNYC/clearpath-web/blob/master/src/pages/main/clearpath-map/map/index.tsx) for our Google Maps key 😉 🌎 
- [ ] Populate dropdown with search recommendations

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- Google Maps API!
