### ISSUE TITLE
☮️ Current Location Pin and Recentering Icon

### ISSUE THREAD

**Issue by szhuang21** [ClearPathNYC/clearpath-web#74]
**Type**: client

**FOF**: 3

## Description
- We want to support various map functionality with user's current location

## Screenshot
<img width="494" alt="image" src="https://user-images.githubusercontent.com/44931711/228631346-c3f0004a-671b-459a-918d-31df9acb9ecc.png">

## Todo

- [ ] Retrieve user's current location
- [ ] Display user's location on map view
- [ ] Center to user's location on command

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- Google Maps!
