### ISSUE TITLE
🏃‍♀️ Build application tracker

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#94]
**Type**: client/api/full stack

**FOF**: 3

## Description
- We want applicants to be able to view their applications and associated statuses
  - Pending
  - Accepted
  - Declined

## Screenshot
<img width="577" alt="image" src="https://user-images.githubusercontent.com/45826922/231290704-f38b35ed-ba5e-45e6-bd72-639dbe0bed34.png">

## Todo

- [ ] Create the new route
  - `/applications`
- [ ] Populate the summary header
- [ ] Populate the applications table
  - Refer to #12    

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- Building a page from start to finish
